### ISSUE TITLE
Repl doesn't work 

### ISSUE THREAD

**Issue by fake-name** [Sapfir0/micropython-uploader#5]
```
λ mploader --repl
Namespace(cache=False, compare=False, config='D:\\Profile\\Desktop\\Repository\\Programming\\ESPScreen\\workSpace\\mploader-config.py', d='.', install_firmware=False, repl=True)
Traceback (most recent call last):
  File "C:\Python38\Scripts\mploader-script.py", line 11, in <module>
    load_entry_point('micropython-uploader==0.3.2', 'console_scripts', 'mploader')()
  File "C:\Python38\lib\site-packages\micropython_uploader-0.3.2-py3.8.egg\upload\uploader.py", line 29, in uploader
  File "C:\Python38\lib\site-packages\micropython_uploader-0.3.2-py3.8.egg\upload\uploader.py", line 40, in startREPL
  File "C:\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

Apparently the repl depends on `picocom` being installed. This is undocumented, and also undiscoverable other then by digging around in the source.

Additionally, there's no picocom builds for windows as well.

**Comment by fake-name** [comment]
Putty works well on windows (it doesn't require all the things installed on the remote device that `rshell` does, and has cli switches.

Something like 

```

def startREPL():
    if 'win32' in sys.platform:
        sub.call(["putty", "-serial", "COM10", "-sercfg", "115200,8,n,1,N"])
    else:
        sub.call(["picocom", "-serial", "-b115200"])
```
seems to work, though I've not figured out how picocom gets the serial port when it is invoked.

There's **lot** of random hard-coded values that make things annoying. `http://micropython.org/resources/firmware/esp8266-20190529-v1.11.bin"`? I'm not using a esp8266, etc...
